build_linux:
  stage: build
  image: blocknetdx/devbuilds:gitlab-linux
  script:
    - "export PROJECTDIR=/opt/blocknetdx/blocknet"
    - "export BASEPREFIX=$PROJECTDIR/depends"
    - "export BASEPREFIX_CACHE=/proj/depends-cache"
    - "export DISTDIR=$PROJECTDIR/dist"
    - "export HOST=x86_64-pc-linux-gnu"
    - "rm -rf \"$BASEPREFIX\""
    - "mv \"$BASEPREFIX_CACHE\" \"$BASEPREFIX\""
    - "mkdir -p $DISTDIR"
    - "chmod +x ./autogen.sh; sync"
    - "./autogen.sh"
    - "CONFIG_SITE=\"$BASEPREFIX/$HOST/share/config.site\" ./configure CC=gcc-8 CXX=g++-8 CFLAGS=\"-g3 -O0\" CXXFLAGS=\"-g3 -O0\" --enable-debug --prefix=/"
    - "make clean"
    - "echo \"Building with cores: 10\""
    - "make -j10"
    - "make install DESTDIR=\"$DISTDIR\""
    - "make clean"
  artifacts:
    name: "scalaris-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux"
    expire_in: 3 weeks
    paths:
      - dist/bin

build_win:
  stage: build
  image: blocknetdx/devbuilds:gitlab-win
  script:
    - "export PROJECTDIR=/opt/blocknetdx/blocknet"
    - "export BASEPREFIX=$PROJECTDIR/depends"
    - "export BASEPREFIX_CACHE=/proj/depends-cache"
    - "export DISTDIR=$PROJECTDIR/dist"
    - "export HOST=x86_64-w64-mingw32"
    - "rm -rf \"$BASEPREFIX\""
    - "mv \"$BASEPREFIX_CACHE\" \"$BASEPREFIX\""
    - "mkdir -p $DISTDIR"
    - "chmod +x ./autogen.sh; sync"
    - "./autogen.sh"
    - "CONFIG_SITE=\"$BASEPREFIX/$HOST/share/config.site\" ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --enable-reduce-exports --disable-bench --disable-gui-tests"
    - "make clean"
    - "echo \"Building with cores: 10\""
    - "make -j10"
    - "make deploy"
    - "make install DESTDIR=\"$DISTDIR\""
    - "cp *win64-setup.exe $DISTDIR/bin/scalaris-win64-setup.exe"
    - "make clean"
  artifacts:
    name: "scalaris-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win"
    expire_in: 3 weeks
    paths:
      - dist/bin

build_mac:
  stage: build
  image: blocknetdx/devbuilds:gitlab-mac
  script:
    - "export PROJECTDIR=/opt/blocknetdx/blocknet"
    - "export BASEPREFIX=$PROJECTDIR/depends"
    - "export BASEPREFIX_CACHE=/proj/depends-cache"
    - "export DISTDIR=$PROJECTDIR/dist"
    - "export HOST=x86_64-apple-darwin14"
    - "rm -rf \"$BASEPREFIX\""
    - "mv \"$BASEPREFIX_CACHE\" \"$BASEPREFIX\""
    - "mkdir -p $DISTDIR"
    - "chmod +x ./autogen.sh; sync"
    - "./autogen.sh"
    - "CONFIG_SITE=\"$BASEPREFIX/$HOST/share/config.site\" ./configure CFLAGS=\"-g3 -O0\" CXXFLAGS=\"-g3 -O0\" --with-gui=qt5 --enable-debug --prefix=/"
    - "make clean"
    - "echo \"Building with cores: 10\""
    - "make -j10"
    - "mkdir -p $DISTDIR/bin && llvm-dsymutil-6.0 src/qt/scalaris-qt -o $DISTDIR/bin/scalaris-qt.dSYM"
    - "make install DESTDIR=\"$DISTDIR\""
    - "make clean"
  artifacts:
    name: "scalaris-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac"
    expire_in: 3 weeks
    paths:
      - dist/bin

test_artifacts:
  stage: test
  image: ubuntu:bionic
  script:
    - "[ -f \"dist/bin/scalaris-cli\" ];"
    - "[ -f \"dist/bin/scalarisd\" ];"
    - "[ -f \"dist/bin/scalaris-qt\" ];"
    - "[ -f \"dist/bin/scalaris-tx\" ];"
    - "[ -f \"dist/bin/scalaris-wallet\" ];"
    - "[ -f \"dist/bin/test_scalaris\" ];"
    - "[ -f \"dist/bin/test_scalaris-qt\" ];"
    - "[ -f \"dist/bin/scalaris-cli.exe\" ];"
    - "[ -f \"dist/bin/scalarisd.exe\" ];"
    - "[ -f \"dist/bin/scalaris-qt.exe\" ];"
    - "[ -f \"dist/bin/scalaris-tx.exe\" ];"
    - "[ -f \"dist/bin/scalaris-wallet.exe\" ];"
    - "[ -f \"dist/bin/test_scalaris.exe\" ];"
    - "[ -f \"dist/bin/scalaris-win64-setup.exe\" ];"
    - "[ -f \"dist/bin/scalaris-cli\" ];"
    - "[ -f \"dist/bin/scalarisd\" ];"
    - "[ -f \"dist/bin/scalaris-qt\" ];"
    - "[ -d \"dist/bin/scalaris-qt.dSYM\" ];"
    - "[ -f \"dist/bin/scalaris-tx\" ];"
    - "[ -f \"dist/bin/scalaris-wallet\" ];"
    - "[ -f \"dist/bin/test_scalaris\" ];"
    - "[ -f \"dist/bin/test_scalaris-qt\" ];"
